### ISSUE TITLE
运行 "Install FlexDecrypt" 错误

### ISSUE THREAD

**Issue by marcocpt** [ChiChou/vscode-frida#10]
错误提示: This command should be used in context menu

**Comment by ChiChou** [comment]
翻译一下

**Comment by marcocpt** [comment]
找了半天,不知道这个上下文菜单在哪里...

**Comment by ChiChou** [comment]
![](https://github.com/ChiChou/vscode-frida/raw/master/resources/doc/flexdecrypt.png)

**Comment by ChiChou** [comment]
0.1.1：在 commad palette 中移除多余明林 https://github.com/ChiChou/vscode-frida/commit/3d5d3aa647afb9ba8a87ec0ee573eecffe91d00e
