### ISSUE TITLE
感觉存在bug，但是未定位出问题

### ISSUE THREAD

**Issue by Dcell** [ChiChou/vscode-frida#14]
环境：
已经安装了 frida-tool，python3，越狱手机也装了frida-server
frida-ps -U 可以正常显示

但是vscode里面。还是显示 ‘unable to connect to remote frida-server’

![截屏2021-03-19 下午2 56 24](https://user-images.githubusercontent.com/4684864/111742523-4aced000-88c3-11eb-9e10-d5a762dd38c2.png)
![截屏2021-03-19 下午2 56 40](https://user-images.githubusercontent.com/4684864/111742540-51f5de00-88c3-11eb-9011-bb6708f0c899.png)

远程到手机，查看进程server应该是正常的。不清楚这个扩展那里有问题。

**Comment by ChiChou** [comment]
你的机器上可能存在多个 python 环境

**Comment by Dcell** [comment]
额... 现在Mac 不都默认带 2.7 和 3.0+  2个python环境么. 
有什么解决方案么

**Comment by ChiChou** [comment]
合并到这个 issue 
https://github.com/ChiChou/vscode-frida/issues/13

**Comment by Dcell** [comment]
Link to #13
