### ISSUE TITLE
Extension crashes without python3 alias

### ISSUE THREAD

**Issue by xyx0826** [ChiChou/vscode-frida#15]
https://github.com/ChiChou/vscode-frida/blob/3122bcce61adcaa3e70fd984ae0d739b03a038ab/src/driver/frida.ts#L24

On my Windows machine I install and run frida through `python`, and `python3` does not exist on my machine. This makes the extension crash when trying to view the Frida Utilities pane and produces an `ENOENT` error.

Suggestion: maybe also try to run python with `python`?

**Comment by ChiChou** [comment]
I think I need to provide a way to choose which python/virtualenv to use, juse like VSCode itself.
Pull requests welcomed

**Comment by xyx0826** [comment]
That would be great. Sadly I'm not quite well versed in TypeScript and extension development.

I see you have a settings key to set the custom IPA file name. One way is to do something similar, provide another settings key to let users set their interpreter path.
