### ISSUE TITLE
不显示越狱应用

### ISSUE THREAD

**Issue by RyanQinqhw** [ChiChou/vscode-frida#19]
这安装完什么都没有， 已经链接越狱设备了， ssh 手机 和 电脑都配置了, 电脑是M1
![image](https://user-images.githubusercontent.com/20712920/124445359-10c20500-ddb2-11eb-8981-1aaace2a16f4.png)

**Comment by ChiChou** [comment]
breaking changes in frida https://github.com/ChiChou/vscode-frida/commit/257171987eb67e282221c8c47055b1b76b0fab7f
