### ISSUE TITLE
Missing "frida" icon at the top of js/typescript document.

### ISSUE THREAD

**Issue by ii64** [ChiChou/vscode-frida#23]
I tried to install the extension from VSCode extension repo, it doesn't shows up the "frida" icon 
![image](https://user-images.githubusercontent.com/26342994/132951898-e3531e27-5b5a-4cb3-9b3f-0811baa83f62.png)

**Comment by ChiChou** [comment]
It’s been removed since the `%load` command in REPL is no longer available

**Comment by ii64** [comment]
We can preload the script using `-l <name>.js`  arg for frida CLI i think

**Comment by yd021976** [comment]
Don't understand, the `%load` command is still available in Frida CLI

**Comment by ChiChou** [comment]
> Don't understand, the `%load` command is still available in Frida CLI

@yd021976 It's back on this year

https://github.com/frida/frida-tools/commit/8fca83f6501c6b54baddb38f72b26ec89885a57c

**Comment by ii64** [comment]
Do we need any modifications?

**Comment by ChiChou** [comment]
@ii64 I'll add it back using `%exec` command

**Comment by ChiChou** [comment]
Also the REPL itself is broken now
https://github.com/frida/frida-tools/pull/113
