### ISSUE TITLE
M1 Macmini 提示 `[Errno 2] No such file or directory: 'frida'`

### ISSUE THREAD

**Issue by xnxin** [ChiChou/vscode-frida#26]
在终端单独运行 `frida` 等命令正常，插件内点击`Spawn Suspended`直接提示 
```
[Errno 2] No such file or directory: 'frida'
Press Enter to continue...
````
其他功能点击正常使用。

**Comment by xnxin** [comment]
自己好了，应该是环境变量问题。

**Comment by Apuyuseng** [comment]
我也遇见这个问题了, python 环境也选择对的.

**Comment by xnxin** [comment]
重启大法好。

**Comment by Apuyuseng** [comment]
[pause.py](https://github.com/ChiChou/vscode-frida/blob/master/backend/pause.py)修改成这样就可以避免问题了.
```python
import subprocess
import sys
import os

def get_environ():
  environ = os.environ
  PATH = [environ['PATH']]
  for p in sys.path:
    if os.path.isdir(p):
        PATH.append(p)
  flag = ':'
  if sys.platform == 'win32':
    flag=';'
  environ['PATH'] = flag.join(PATH)


if len(sys.argv) > 1:
  env = get_environ()
  try:
    subprocess.check_call(sys.argv[1:], env=env)
  except (subprocess.SubprocessError, FileNotFoundError) as e:
    print(e)
  finally:
    input('Press Enter to continue...')

```

找到插件目录,比如`linux`、`mac` 的在用户`/Users/xxx/.vscode/extensions/codecolorist.vscode-frida-x.x.xx/backend`

**Comment by ChiChou** [comment]
取 Python 路径的代码实际上在 https://github.com/ChiChou/vscode-frida/blob/be75bbc6239246e0af88717ff2907eb172ea0d2d/src/utils.ts#L39

> [pause.py](https://github.com/ChiChou/vscode-frida/blob/master/backend/pause.py)修改成这样就可以避免问题了.
> 
> ```python
> import subprocess
> import sys
> import os
> 
> def get_environ():
>   environ = os.environ
>   PATH = [environ['PATH']]
>   for p in sys.path:
>     if os.path.isdir(p):
>         PATH.append(p)
>   flag = ':'
>   if sys.platform == 'win32':
>     flag=';'
>   environ['PATH'] = flag.join(PATH)
> 
> 
> if len(sys.argv) > 1:
>   env = get_environ()
>   try:
>     subprocess.check_call(sys.argv[1:], env=env)
>   except (subprocess.SubprocessError, FileNotFoundError) as e:
>     print(e)
>   finally:
>     input('Press Enter to continue...')
> ```
> 
> 找到插件目录,比如`linux`、`mac` 的在用户`/Users/xxx/.vscode/extensions/codecolorist.vscode-frida-x.x.xx/backend`

@Apuyuseng 

取 Python 路径的代码实际上在 https://github.com/ChiChou/vscode-frida/blob/be75bbc6239246e0af88717ff2907eb172ea0d2d/src/utils.ts#L39

也就是和 Python 插件用的设置是同步的。

正确的办法是用命令面板 Select Python Interpreter

![image](https://user-images.githubusercontent.com/2802045/160497828-a2e59b71-ca2a-468e-8ab8-41d9891679b5.png)

**Comment by Apuyuseng** [comment]
python 执行py文件是没有问题的, 所以界面的上相关app是显示的, 问题是在`pause.py`是进行了命令执行(frida相关命令),  frida 执行文件并不再环境变量PATH中.
<img width="600" alt="报错图" src="https://user-images.githubusercontent.com/17330686/160514097-9066e68e-bc45-416e-81c5-2ff844b2aaae.png">

<img width="600" alt="命令可正常执行" src="https://user-images.githubusercontent.com/17330686/160514216-38964e4e-d9b8-4a88-b15c-151d3d29297d.png">

**Comment by ChiChou** [comment]
更新 v0.3.16，请稍候 VSCode Market 刷新缓存

**Comment by Apuyuseng** [comment]
感谢, 得到解决了
