### ISSUE TITLE
Unable to establish SSH connection to device: FoulDecrypt

### ISSUE THREAD

**Issue by GreenglassT** [ChiChou/vscode-frida#34]
I am attempting to use FoulDecrypt to decrypt applications, but keep getting refused through ssh

I have FoulDecrypt, Zip, and OpenSSH installed on my iPhone

Should I generate an SSH key on my iPhone or my Mac? Where do I put this SSH key?

**Comment by GreenglassT** [comment]
> Yes you need `ssh-copy-id`. I need to improve the experience of this part a bit

Where do I do` ssh-copy-id`? I'm brand new to VSCode

**Comment by GreenglassT** [comment]
I have found the Install SSH Public Key command on the VSCode extension, pushed the id_rsa file to my iPhone, but I still cannot run establish an SSH connection.

**Comment by ChiChou** [comment]
> I have found the Install SSH Public Key command on the VSCode extension, pushed the id_rsa file to my iPhone, but I still cannot run establish an SSH connection.
> 
> I can connect through opening a shell through the extension, as well as open apps.

Are you using the dropbear on port 44? I recently found that `ssh-copy-id` doesn't seem to work with it

**Comment by GreenglassT** [comment]
No, I'm not sure what dropbear is. I usually use iproxy on port 22. I can run Frida through my terminal just fine as well.

**Comment by ChiChou** [comment]
Dropbear is the default SSH server on some jailbreaks (e.g. checkra1n). You need to install OpenSSH from Cydia if that’s the case

**Comment by GreenglassT** [comment]
Hmmm, I have OpenSSH installed

**Comment by ChiChou** [comment]
> I can connect through opening a shell through the extension

You meant opening SSH shell?

**Comment by GreenglassT** [comment]
> You meant opening SSH shell?

Correct! Trying it out again. Fresh install and we shall se how it works out.

**Comment by dlevi309** [comment]
> > I can connect through opening a shell through the extension
> 
> You meant opening SSH shell?

what jailbreak are you using? (checkra1n, unc0ver, taurine, etc.)

**Comment by GreenglassT** [comment]
Odysseyra1n. I'm using openssh on port 22. I have authorized keys so I can ssh into my phone from my mac and vice versa. But this VSCode extension refuses to work for me.

**Comment by ChiChou** [comment]
> Odysseyra1n. I'm using openssh on port 22. I have authorized keys so I can ssh into my phone from my mac and vice versa. But this VSCode extension refuses to work for me.

It's just some command line wrapper based on `ssh`. If your `ssh` cli works there should be no problem

**Comment by ChiChou** [comment]
Could be something wrong with `iproxy` command line interface. I use pure python implementation (which is much slower of course) in the latest release

**Comment by ChiChou** [comment]
Since FoulDecrypt has been removed from this tool, I am closing all issues related to it
