### ISSUE TITLE
Exited with ENOENT Error: Failed to execute driver, arguments: devices

### ISSUE THREAD

**Issue by farendaibiao** [ChiChou/vscode-frida#40]
I delete Python 3.7 and install 3.10
it can't work!
The log: 
Error: Failed to execute driver, arguments: devices

Exited with ENOENT

also
AttributeError: 'REPLApplication' object has no attribute '_eval_and_print'. Did you mean: '_exec_and_print'?

**Comment by ChiChou** [comment]
AttributeError 是 frida-tools 自己的 bug，在新版本发布之前可以自己找到 frida-tools 的安装路径按照这里修改
https://github.com/frida/frida-tools/pull/113/files
