### ISSUE TITLE
can't dump ipa

### ISSUE THREAD

**Issue by piaoapiao** [ChiChou/vscode-frida#45]
can't dump ipa
FoulDecrypt running: Creating bundle archive

 I have install fouldecrypt and zip  on iPhone , have config .sshh 

after read document, I doubt that I don't  execute "Install FoulDecrypt " command. 

where to execute the command ?

**Comment by ChiChou** [comment]
Now FoulDecrypt has been removed in favor of [bagbak](https://github.com/chichou/babgak)
