### ISSUE TITLE
端口映射后访问超时问题

### ISSUE THREAD

**Issue by xiaooojun** [ChiChou/vscode-frida#49]
debug with lldb 后，pcc 连接超时。看了下端口日志，端口有做映射，但访问有些问题。

**Comment by ChiChou** [comment]
已知 bug，但是目前我也搞不清楚怎么回事..

**Comment by xiaooojun** [comment]
Mac上是否可以换成iproxy 22 22 类似的命令做映射。看了下电脑端的端口日志，工具里的端口转发的是以开头的进程Python开头的。

**Comment by ChiChou** [comment]
https://github.com/ChiChou/fruity-frida/blob/main/tools/debug.ts

现在把 lldb 调试功能单独拿到一个 npm 包实现了
