### ISSUE TITLE
原谅我没看懂如何app上右键选择加载js脚本并附加上去

### ISSUE THREAD

**Issue by HuRuWo** [ChiChou/vscode-frida#5]
如果我写了1.js的脚本 如何在应用列表里选择并附加上去
代替 `frida -U -f com.xxx.xxx -l 1.js --no-pause` 这个语句的快捷操作

**Comment by ChiChou** [comment]
1. 选中任何一个应用打开 REPL 并保持
2. 打开 `.js` 文件
3. 点击编辑器右上角图标运行 js

**Comment by zhangxufengde** [comment]
> 1. 选中任何一个应用打开 REPL 并保持
> 2. 打开 `.js` 文件
> 3. 点击编辑器右上角图标运行 js

你好，我这边这样测试了 实际是执行了 %load  xxxxxxxxxx/code.js ， 但是脚本加载不进去，单独写%load  xxxxxxxxxx/code.js 这个命令也加载不进去，但是frida -U -l  code.js  xxx  脚本可以加载进去，我电脑和手机frida环境都是 14.1.3  。

**Comment by ChiChou** [comment]
没有复现步骤，没有具体报错

**Comment by zhangxufengde** [comment]
> 没有复现步骤，没有具体报错

就是先附加上应用，然后%load  zzzz/code.js  加载js脚本，运行完没有一点报错，终端也没有log,也没有执行js里面的函数，正常的加载完会执行js里面的函数的(已经在js里面调用了)，我查看了官方文档 Frida CLI 也没有发现%load 命令

**Comment by ChiChou** [comment]
@zhangxufengde 应该是 frida-tools 的 bug，去找作者反馈了

**Comment by ChiChou** [comment]
@zhangxufengde %load 命令在某一个版本的 frida-tools 被去掉了，先暂时移除这个功能，换别的实现方式

**Comment by Primer1889** [comment]
AttributeError: 'REPLApplication' object has no attribute '_eval_and_print'

**Comment by ChiChou** [comment]
@Primer1889 `pip install -U frida-tools`
