### ISSUE TITLE
Frida: Get typing hint for frida Command Error (Cannot create process, error code : 193)

### ISSUE THREAD

**Issue by BomyeongSong** [ChiChou/vscode-frida#50]
The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 193).
![image](https://github.com/ChiChou/vscode-frida/assets/135289917/cf623102-3cbe-47fa-811b-8c45599410cf)

I solved it by changing this code :
from \codecolorist.vscode-frida-0.7.0\out\commands\typing.js :
```
function npmInstall() {
    const name = `npm`;
    const shellPath = 'npm';

...
```
that
```
function npmInstall() {
    const name = `npm`;
    const shellPath = 'npm.cmd';

...
```

any other solution ?

**Comment by ChiChou** [comment]
Good catch. 

https://github.com/ChiChou/vscode-frida/blob/main/src/commands/typing.ts#L11

It should be `executable("npm")`, like this

https://github.com/ChiChou/vscode-frida/blob/main/src/commands/lldb.ts#L32

**Comment by BomyeongSong** [comment]
It's not a .exe file, but a .bat file.

![image](https://github.com/ChiChou/vscode-frida/assets/135289917/effd6416-9021-459c-b480-96865c1adb0b)

![image](https://github.com/ChiChou/vscode-frida/assets/135289917/96e55e90-dc53-4d3b-a472-d928d35b453f)

**Comment by ChiChou** [comment]
Windows is 💩 for real
