### ISSUE TITLE
 How to configure the path of python？

### ISSUE THREAD

**Issue by arenaswan** [ChiChou/vscode-frida#52]
hi,ChiChou.
I tried to connect to my wsa environment, but he prompted "the specified GDB remote stub cannot be reached: Could not connect to 127.0.0.1: ����Ŀ�����������ܾ����޷����ӡ�"
I suspect it was due to an incorrect configuration of my Python path,how to configure it?

**Comment by ChiChou** [comment]
insufficient information provided

**Comment by ChiChou** [comment]
The error information doesn't look like it has anything to do with this extension. Please at lease give basic instructions to reproduce instead of guessing the root cause

**Comment by ChiChou** [comment]
@evowizz fixed in 0.7.5. Might take a while to roll the update
