### ISSUE TITLE
Debug with lldb failure

### ISSUE THREAD

**Issue by dev-jw** [ChiChou/vscode-frida#55]
when I already install [fruity-frida](https://github.com/chichou/fruity-frida)，and in itrem2 can use command —— ios-debug

but in vscode， Running 『debug with lldb』 will result in an error —— Command not found: ios-debug

Terminal process start failed: the path to the shell executable "ios-debug" does not exist.

**Comment by ChiChou** [comment]
不知什么原因你的 VSCode 内置 terminal 的 PATH 和 iTerm 配置不一致

可以尝试参考这个修改
https://stackoverflow.com/a/45637716
