### ISSUE TITLE
功能增强

### ISSUE THREAD

**Issue by 456vv** [ChiChou/vscode-frida#57]
![2024-06-21_162009](https://github.com/ChiChou/vscode-frida/assets/3807318/becb23f1-1853-488e-8d54-4a69cfc516c2)

连接失败后，无法删除，也无法重新增加。仅重新打开vscode才后才消失。
支持列表过滤，仅显示需要的appp
增加保留连接过的记录，方便下次使用。
使用spawn时候，带上 -f 和 -l 参数
![image](https://github.com/ChiChou/vscode-frida/assets/3807318/e41e48be-efb3-491f-bca0-30d77682f0bd)

**Comment by ChiChou** [comment]
很多需求啊，请捐款
