### ISSUE TITLE
Error:c:\Users\.vscode\extensions\codecolorist.vscode-frida-0.0.4\out\driver\frida.js:36:24

### ISSUE THREAD

**Issue by paynexss** [ChiChou/vscode-frida#6]
![image](https://user-images.githubusercontent.com/5448638/89271484-5a204680-d66f-11ea-986b-44ed04e3bc55.png)

**Comment by ChiChou** [comment]
Did you install `frida-tools`?

**Comment by paynexss** [comment]
@ChiChou I did not rename python3
