### ISSUE TITLE
FlexDecrypt requires these command(s) to be installed on device: zip, flexdecrypt. 

### ISSUE THREAD

**Issue by mrfuturman** [ChiChou/vscode-frida#8]
Error running command frida.external.flexdecrypt: FlexDecrypt requires these command(s) to be installed on device: zip, flexdecrypt. This is likely caused by the extension that contributes frida.external.flexdecrypt.
设备有装这2个

**Comment by ChiChou** [comment]
贴一下 OUTPUT 窗口里的 _Frida Extension_ 输出日志

**Comment by ZHDeveloper** [comment]
> 贴一下 OUTPUT 窗口里的 _Frida Extension_ 输出日志
> ![image](https://user-images.githubusercontent.com/2802045/89612413-56303680-d8b2-11ea-9d1a-d120acb794bc.png)

Exited with 255
Error: Failed to execute driver, arguments: apps e110042e71695d65deb18b53527bedc25e4f2f13
unable to connect (connection refused)

**Comment by ZHDeveloper** [comment]
> 贴一下 OUTPUT 窗口里的 _Frida Extension_ 输出日志
> ![image](https://user-images.githubusercontent.com/2802045/89612413-56303680-d8b2-11ea-9d1a-d120acb794bc.png)

终端进程“frida '22694', '--device', 'e110042e71695d65deb18b53527bedc25e4f2f13'”已终止，退出代码: 1。

**Comment by mrfuturman** [comment]
![image](https://user-images.githubusercontent.com/60970770/89641005-572d8c00-d8e3-11ea-8d63-45b72322538b.png)
output没内容。我把手机的frida和电脑的版本号也更新一致了。
iPhone6 12.4.7
frida-ios-dump可以砸壳

**Comment by mrfuturman** [comment]
Error: Failed to execute driver, arguments: apps e4b4ba85b52c87fffb851a4a9de4a6cc167c2cbf
unable to connect (connection refused)


Exited with 255

**Comment by ChiChou** [comment]
> Error: Failed to execute driver, arguments: apps e4b4ba85b52c87fffb851a4a9de4a6cc167c2cbf
> 
> unable to connect (connection refused)
> 
> 
> 
> 
> 
> Exited with 255

连 lockdown 都连不上，你是不是用的 Windows 而且没有装 iTunes（iPhone usb 驱动）

**Comment by ZHDeveloper** [comment]
> iPhone

Mac系统也是这样

**Comment by ChiChou** [comment]
1. 先 `ssh-keygen` 生成 `~/.ssh/id_rsa.pub`
2. 右键设备节点，Install SSH Public Key
3. 确认右键设备节点之后 Open Shell 命令不再提示输入密码

**Comment by mrfuturman** [comment]
![image](https://user-images.githubusercontent.com/60970770/90401069-0599b400-e0d0-11ea-9a6e-82ef4219eecf.png)
砸壳成功了，谢谢。otool -l 看可执行文件也解密了，但是app安装后闪退。看了CRASH-log，好像是framework的问题，但是用其他的方法砸壳可以直接安装。
随便贴一个
![image](https://user-images.githubusercontent.com/60970770/90408171-12bba080-e0da-11ea-850f-2e4540663c8c.png)
我再试试。感谢大佬

**Comment by ChiChou** [comment]
terminal 异常退出，这是失败了

**Comment by ChiChou** [comment]
FlexDecrypt 已替换为 [FoulDecrypt](https://github.com/NyaMisty/fouldecrypt)
